<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'code' => 'CL',
                'name' => 'Chile',
                'currency_code' => 'CLP',
                'currency_symbol' => '$',
                'currency_decimals' => 0,
                'locale' => 'es-CL',
                'timezone' => 'America/Santiago',
                'phone_code' => '+56',
                'tax_name' => 'IVA',
                'tax_rate' => 19.00,
                'fiscal_id_label' => 'RUT',
                'fiscal_id_pattern' => '/^\d{7,8}[\dkK]$/',
                'date_format' => 'DD/MM/YYYY',
                'is_active' => true,
            ],
            [
                'code' => 'CO',
                'name' => 'Colombia',
                'currency_code' => 'COP',
                'currency_symbol' => '$',
                'currency_decimals' => 0,
                'locale' => 'es-CO',
                'timezone' => 'America/Bogota',
                'phone_code' => '+57',
                'tax_name' => 'IVA',
                'tax_rate' => 19.00,
                'fiscal_id_label' => 'NIT',
                'fiscal_id_pattern' => '/^\d{9,10}$/',
                'date_format' => 'DD/MM/YYYY',
                'is_active' => true,
            ],
            [
                'code' => 'PE',
                'name' => 'Perú',
                'currency_code' => 'PEN',
                'currency_symbol' => 'S/',
                'currency_decimals' => 2,
                'locale' => 'es-PE',
                'timezone' => 'America/Lima',
                'phone_code' => '+51',
                'tax_name' => 'IGV',
                'tax_rate' => 18.00,
                'fiscal_id_label' => 'RUC',
                'fiscal_id_pattern' => '/^\d{11}$/',
                'date_format' => 'DD/MM/YYYY',
                'is_active' => true,
            ],
            [
                'code' => 'AR',
                'name' => 'Argentina',
                'currency_code' => 'ARS',
                'currency_symbol' => '$',
                'currency_decimals' => 2,
                'locale' => 'es-AR',
                'timezone' => 'America/Argentina/Buenos_Aires',
                'phone_code' => '+54',
                'tax_name' => 'IVA',
                'tax_rate' => 21.00,
                'fiscal_id_label' => 'CUIT',
                'fiscal_id_pattern' => '/^\d{11}$/',
                'date_format' => 'DD/MM/YYYY',
                'is_active' => true,
            ],
            [
                'code' => 'BO',
                'name' => 'Bolivia',
                'currency_code' => 'BOB',
                'currency_symbol' => 'Bs',
                'currency_decimals' => 2,
                'locale' => 'es-BO',
                'timezone' => 'America/La_Paz',
                'phone_code' => '+591',
                'tax_name' => 'IT',
                'tax_rate' => 13.00,
                'fiscal_id_label' => 'NIT',
                'fiscal_id_pattern' => '/^\d{7,10}$/',
                'date_format' => 'DD/MM/YYYY',
                'is_active' => true,
            ],
            [
                'code' => 'US',
                'name' => 'Estados Unidos',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'currency_decimals' => 2,
                'locale' => 'en-US',
                'timezone' => 'America/New_York',
                'phone_code' => '+1',
                'tax_name' => 'Sales Tax',
                'tax_rate' => 0.00,
                'fiscal_id_label' => 'EIN',
                'fiscal_id_pattern' => null,
                'date_format' => 'MM/DD/YYYY',
                'is_active' => true,
            ],
            [
                'code' => 'BR',
                'name' => 'Brasil',
                'currency_code' => 'BRL',
                'currency_symbol' => 'R$',
                'currency_decimals' => 2,
                'locale' => 'pt-BR',
                'timezone' => 'America/Sao_Paulo',
                'phone_code' => '+55',
                'tax_name' => 'ICMS',
                'tax_rate' => 17.00,
                'fiscal_id_label' => 'CNPJ',
                'fiscal_id_pattern' => '/^\d{14}$/',
                'date_format' => 'DD/MM/YYYY',
                'is_active' => true,
            ],
            [
                'code' => 'VE',
                'name' => 'Venezuela',
                'currency_code' => 'VES',
                'currency_symbol' => 'Bs',
                'currency_decimals' => 2,
                'locale' => 'es-VE',
                'timezone' => 'America/Caracas',
                'phone_code' => '+58',
                'tax_name' => 'IVA',
                'tax_rate' => 16.00,
                'fiscal_id_label' => 'RIF',
                'fiscal_id_pattern' => '/^[JVEPDCG]\d{8,10}$/',
                'date_format' => 'DD/MM/YYYY',
                'is_active' => true,
            ],
            [
                'code' => 'UY',
                'name' => 'Uruguay',
                'currency_code' => 'UYU',
                'currency_symbol' => '$',
                'currency_decimals' => 2,
                'locale' => 'es-UY',
                'timezone' => 'America/Montevideo',
                'phone_code' => '+598',
                'tax_name' => 'IVA',
                'tax_rate' => 22.00,
                'fiscal_id_label' => 'RUT',
                'fiscal_id_pattern' => '/^\d{12}$/',
                'date_format' => 'DD/MM/YYYY',
                'is_active' => true,
            ],
            [
                'code' => 'PY',
                'name' => 'Paraguay',
                'currency_code' => 'PYG',
                'currency_symbol' => '₲',
                'currency_decimals' => 0,
                'locale' => 'es-PY',
                'timezone' => 'America/Asuncion',
                'phone_code' => '+595',
                'tax_name' => 'IVA',
                'tax_rate' => 10.00,
                'fiscal_id_label' => 'RUC',
                'fiscal_id_pattern' => '/^\d{6,8}$/',
                'date_format' => 'DD/MM/YYYY',
                'is_active' => true,
            ],
            [
                'code' => 'GT',
                'name' => 'Guatemala',
                'currency_code' => 'GTQ',
                'currency_symbol' => 'Q',
                'currency_decimals' => 2,
                'locale' => 'es-GT',
                'timezone' => 'America/Guatemala',
                'phone_code' => '+502',
                'tax_name' => 'IVA',
                'tax_rate' => 12.00,
                'fiscal_id_label' => 'NIT',
                'fiscal_id_pattern' => '/^\d{8,12}$/',
                'date_format' => 'DD/MM/YYYY',
                'is_active' => true,
            ],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['code' => $country['code']],
                $country
            );
        }
    }
}
