[program:aldia-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /home/forge/aldiaproyect/artisan queue:work database --sleep=3 --tries=3 --max-time=3600 --queue=default --memory=256 --timeout=120
directory=/home/forge/aldiaproyect
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=forge
numprocs=4
startretries=3
redirect_stderr=true
stdout_logfile=/home/forge/aldiaproyect/storage/logs/worker.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stopwaitsecs=120
