[program:aldia-reverb]
process_name=%(program_name)s
command=php /home/forge/aldiaproyect/artisan reverb:start
directory=/home/forge/aldiaproyect
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=forge
numprocs=1
startretries=3
redirect_stderr=true
stdout_logfile=/home/forge/aldiaproyect/storage/logs/reverb.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stopwaitsecs=60
environment=BROADCAST_CONNECTION="reverb"
